# This file is provided so that the application can be compiled using Twister,
# the Zephyr testing tool. In this file, multiple combinations can be specified,
# so that you can easily test all of them locally or in CI.
sample:
  description: GET Smart Wireless Lighting System Controller (https://download.schneider-electric.com/files?p_Doc_Ref=AR1053-161105&p_enDocType=User+guide&p_File_Name=smart-wireless-lighting-user-guide.pdf)
  name: GET Smart Controller
common:
  build_only: true
  integration_platforms:
    - esp32s3-devkitm
tests:
  app.default: {}
  app.debug:
    extra_overlay_confs:
      - debug.conf
